.TH DOCSIM 1
.SH NAME
docsim \- score similarity between text documents
.SH SYNOPSIS
.B docsim
[\fIOPTIONS\fR] \fB\-\-query \fIFILE\fR [\fIPATH\fR...]
.SH DESCRIPTION
.B docsim
compares one file (the \fIquery\fR) with every other text file in the current
directory and sorts them according to their textual similarity.
.PP
docsim's default behavior is parse the words out of each file (including the
query), pass them through a stoplist to remove common English words, remove
suffixes from each word with Porter stemming, perform TF-IDF to weight terms
within the document and within the corpus, and report the cosine simularity
between every document and the query.
.SS Working with non-English documents or source code
.PP
docsim works best with English text documents, since the included stoplist and
stemming algorithm both operate on English words. Results won't be quite as
good, but those features can be disabled with the \fV\-\-no\-stemming\fR and
\fV\-\-no\-stoplist\fR flags:
.IP
.nf
\f[C]
docsim --query demando.txt --no-stoplist --no-stemming ~/esperanto_notes
\f[R]
.fi
.PP
Similarly, the same flags can be applied to a repository of source code.
Operators (like \fV;\fR and \fV+=\fR) won't factor into the comparison, but
identifiers and keywords will.
.IP
.nf
\f[C]
docsim --query main.c --no-stoplist --no-stemming **/*.c
\f[R]
.fi
.SH OPTIONS
.TP
.BR \-\-best\-first
When enabled, docsim will sort results from best to worst, instead of the
default (worst to best).
.TP
.BR \-\-follow\-symlinks
Parse symbolic links in the search path. Default behavior is to ignore symlinks.
.TP
.BR \-\-limit " " \fINUM\fR
Show no more that the best NUM results.
.TP
.BR \-\-no\-stemming
Don't stem words. Stemming reduces inflected words to their word stem before
comparing documents, which maps morphologically related words to a common term
(so "spinning", "spinner", and "spins" might all map to "spin").
.PP
.RS
Stemming usually improves scoring accuracy in English, but should probably be
disabled when searching across code or documents in other languages.
.RE
.TP
.BR \-\-no\-stoplist
Don't filter out common words, like "the" and "because".
.TP
.BR \-\-omit\-query
Don't include the query document itself in the results, even if it's in a
directory being searched.
.TP
.BR \-\-query " " \fIFILE\fR
Use \fIFILE\fR as the query against which all other files will be compared.
.TP
.BR \-\-show\-scores
Include the cosine similarity between each document and the query in the results.
.TP
.BR \-\-stoplist " " \fISTOPLIST\fR
Provide a custom stoplist to use instead of the default English stoplist.
\fISTOPLIST\fR should be a text file with one word per line. Those words will be
excluded from textual analysis.
.PP
.RS
Generally stoplists are filled with common words (like "the" and "because" in
English, or "char" and "struct" in C) that don't carry significant semantic
value.
.RE
.TP
.BR \-\-verbose
Print extra debugging information.
.LP
.SH BUGS
Please report bugs if you find them:
.BR https://github.com/hrs/docsim/issues
.SH AUTHOR
Harry R. Schwartz <hello@harryrschwartz.com>
