project_name: docsim

before:
  hooks:
    - sh -c "gzip -c -n -9 ./manpages/docsim.1 > ./manpages/docsim.1.gz"

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    rlcp: true
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE.md
      - manpages/*

brews:
  - folder: Formula
    tap:
      owner: hrs
      name: homebrew-docsim
      branch: main
      token: "{{ .Env.GITHUB_TOKEN }}"
    goarm: "7"
    description: Local, in-memory search tool, ranking results by textual similarity.
    homepage: https://github.com/hrs/docsim
    license: GPL-3.0-or-later
    test: system "make test"
    install: |-
      bin.install "docsim"
      man1.install "manpages/docsim.1"

nfpms:
  - maintainer: Robin Schwartz <hello@robinschwartz.me>
    description: |-
      Local, in-memory search tool, ranking results by textual similarity.
      Docsim uses information retrieval techniques (like stemming and TF-IDF) to
      parse text documents and rank them by similarity to a given query. It's
      like a local search engine for your notes or code.
    bindir: /usr/bin
    section: utils
    homepage: https://github.com/hrs/docsim
    license: GPLv3
    contents:
      - src: ./manpages/docsim.1.gz
        dst: /usr/share/man/man1/docsim.1.gz
        file_info:
          mode: 0644
      - src: ./debian/copyright
        dst: /usr/share/doc/docsim/copyright
        file_info:
          mode: 0644
    formats:
      - deb
      - rpm
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package
