name: Check version
on:
  pull_request:
  push:
    branches:
      - main
permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
        id: go

      - name: Show latest version tag
        run: "git tag | grep -E '^v[0-9]+\\.[0-9]+\\.[0-9]+' | tail -1 | sed s/v//"
