name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        id: go

      - name: Run tests
        run: 'make && make test'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASER_GITHUB_TOKEN }}
